version: '3'
services: 
  
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network
    volumes:
      - mariadb-data:/var/lib/mysql
  
#  pfsoa_service:
#    image: foto_app:v6
#    restart: always
#    ports:
#      - 8103:80
#    networks: 
#      - internal-container-network
#    volumes:
#      - sqldata:/root/.aspnet/DataProtection-Keys
#    depends_on:
#      - db
  

volumes:
 mariadb-data:
 sqldata:
networks:
 internal-container-network:
  driver: bridge
